# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "entities", :force => true do |t|
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "entity_type",    :string
    t.column "access_control", :text
    t.column "specification",  :text
  end

  create_table "events", :force => true do |t|
    t.column "created_at",    :datetime
    t.column "event_type",    :string
    t.column "specification", :text
    t.column "state",         :string
  end

  create_table "links", :force => true do |t|
    t.column "entity_id",     :integer
    t.column "omrl",          :string
    t.column "link_type",     :string
    t.column "specification", :text
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

end
